# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e09bdd4c8d89dc25f25b45d3691b96f12b7db1bdfd6973925f041c55cc1638dd5e47839fb972e960db09555f0040c2ec9e048369382c16b50befe11e51e4eb3e

test:
  secret_key_base: d8a52b888c1d88e368d2c1323ddc803981ffcded8059648597d89070156b1c5a29fbe2e5efde35f44058abd17c9d3843e155bf4bc31e6f9fe397ebc0b946f565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
